# Generated by Django 4.0.5 on 2023-04-03 15:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_form_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='form_button',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='form_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='header_slogan',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='header_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='insta_block',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraphe', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False))])), ('link_button', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.RichTextBlock(required=False))])), ('social_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False))]))], use_json_field=None),
        ),
    ]
