# Generated by Django 4.0.5 on 2023-04-03 15:41

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_form_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_slogan',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_title',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
