# Generated by Django 4.0.5 on 2023-04-03 15:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_header_slogan_homepage_header_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraphe', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False))])), ('link_button', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.URLBlock(required=False))])), ('social_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False))]))], use_json_field=None),
        ),
    ]
