# Generated by Django 4.0.5 on 2023-04-03 15:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_title', wagtail.fields.RichTextField(blank=True, null=True)),
                ('header_slogan', wagtail.fields.RichTextField(blank=True, null=True)),
                ('body', wagtail.fields.StreamField([('paragraphe', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False))])), ('link_button', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False)), ('link', wagtail.blocks.URLBlock(required=False))])), ('social_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(required=False))]))], use_json_field=None)),
                ('header_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
